application:
    mode: bootstrap
    error_seed: 2006
    error_scaling: pop
    # winners_only:  false     # optional: drop non-winner bidders
    # capacity_source: initial # optional: 'initial' | 'last_round'
    modular_regressors:
        - elig_pop
    quadratic_regressors:
        - adjacency
        - pop_centroid_delta4
        - air_travel
        - travel_survey
    quadratic_id_regressors:
        - elig_adjacency
        - elig_pop_centroid_delta4
        - elig_air_travel
        - elig_travel_survey
    counterfactual:
        iv: far_ramp1000_2000_popexog
        sample: all
        pop_threshold: .inf

dimensions:
    n_simulations: 10

subproblem:
    name: QuadraticKnapsackGRB
    gurobi_params:
        TimeLimit: 10.0

row_generation:
    max_iters: 200
    tolerance: .00001
    master_gurobi_params:
        Method: -1
    theta_bounds:
        lb: -50
        ub: 50
        lbs:
            elig_pop: -50
            adjacency: -50
            pop_centroid_delta4: -50
            air_travel: -50
            travel_survey: -50
            elig_adjacency: -50
            elig_pop_centroid_delta4: -50
            elig_air_travel: -50
            elig_travel_survey: -50
        ubs:
            elig_pop: 50
            adjacency: 50
            pop_centroid_delta4: 50
            air_travel: 50
            travel_survey: 50
            elig_adjacency: 50
            elig_pop_centroid_delta4: 50
            elig_air_travel: 50
            elig_travel_survey: 50
bootstrap:
    num_samples: 50
    seed: 1233
    rowgen_tol: 0.00001
    rowgen_max_iters: 300
    master_gurobi_params:
        Method: -1

callbacks:
    row_gen:
        - {iters: 70, timeout: 2.0}
        - {iters: 5, timeout: 10.0}
        - {iters: 100, timeout: 60.0, retire: true}
    boot:
        - {iters: 50, timeout: 2.0}
        - {iters: 5,  timeout: 10.0, retire: true}
        - {iters: 1,  timeout: 30.0, retire: true}
        - {iters: 20, timeout: 2.0}
        - {iters: 5,  timeout: 10.0, retire: true}
        - {iters: 1,  timeout: 30.0, retire: true}
        - {iters: 20, timeout: 2.0}
        - {iters: 5,  timeout: 10.0, retire: true}
        - {iters: 1,  timeout: 30.0, retire: true}
        - {iters: 30, timeout: 2.0}
        - {iters: 5,  timeout: 10.0, retire: true}
        - {iters: 1,  timeout: 30.0, retire: true}
    boot_strip:
        percentile: 95
        hard_threshold: 5000
