application:
    mode: bootstrap
    error_seed: 2006
    error_scaling: pop
    # winners_only:  false     # optional: drop non-winner bidders
    # capacity_source: initial # optional: 'initial' | 'last_round'
    modular_regressors:
        - elig_pop
    quadratic_regressors:
        - adjacency
        - pop_centroid_delta4
        - air_travel
        - travel_survey
    quadratic_id_regressors:
        - elig_adjacency
        - elig_pop_centroid_delta4
        - elig_air_travel
        - elig_travel_survey
    counterfactual:
        iv: out_w2
        sample: all
        pop_threshold: .inf

dimensions:
    n_simulations: 1

subproblem:
    name: QuadraticKnapsackGRB
    gurobi_params:
        TimeLimit: 1.0

row_generation:
    max_iters: 1
    tolerance: .00001
    master_gurobi_params:
        Method: -1
    theta_bounds:
        lb: -200
        ub: 1000
        lbs:
            elig_pop: -50
            adjacency: -50
            pop_centroid_delta4: -50
            air_travel: -50
            travel_survey: -50
            elig_adjacency: -50
            elig_pop_centroid_delta4: -50
            elig_air_travel: -50
            elig_travel_survey: -50
        ubs:
            elig_pop: 50
            adjacency: 50
            pop_centroid_delta4: 50
            air_travel: 50
            travel_survey: 50
            elig_adjacency: 50
            elig_pop_centroid_delta4: 50
            elig_air_travel: 50
            elig_travel_survey: 50
bootstrap:
    num_samples: 2
    seed: 1233
    rowgen_tol: 0.00001
    rowgen_max_iters: 1

callbacks:
    row_gen:
        - {iters: 100, timeout: 1.0, retire: true}
    boot:
        - {iters: 50, timeout: 1.0, retire: true}
    boot_strip:
        percentile: 95
        hard_threshold: 100000
