application:
    dataset: c_block
    item_modular: fe
    mode: bootstrap
    error_seed: 2006
    error_scaling: pop
    winners_only: true
    capacity_source: last_round
    modular_regressors:
        - elig_pop
    quadratic_regressors:
        - adjacency
        - pop_centroid_delta4
    quadratic_id_regressors:
        - elig_adjacency
dimensions:
    n_simulations: 20
subproblem:
    name: QuadraticKnapsackGRB
    gurobi_params:
        TimeLimit: 1.0

row_generation:
    max_iters: 100
    tolerance: .01
    master_gurobi_params:
        Method: 0
    theta_bounds:
        lb: -200
        ub: 2000
        lbs:
            elig_pop: -2000
            adjacency: -2000
            pop_centroid_delta4: -2000
            elig_adjacency: -2000
        ubs:
            elig_pop: 3000

bootstrap:
    num_samples: 150
    seed: 1233
    rowgen_tol: 0.001
    rowgen_max_iters: 250

callbacks:
    row_gen:
        - {iters: 50, timeout: 1.0}
        - {timeout: 5.0, retire: true}
    boot:
        - {iters: 10, timeout: 1.0}
        - {iters: 2, timeout: 5.0, retire: true}
        - {iters: 10, timeout: 1.0}
        - {iters: 2, timeout: 5.0, retire: true}
        - {iters: 10, timeout: 1.0}
        - {iters: 20, timeout: 1.0, retire: true}
        - {iters: 20, timeout: 1.0, retire: true}
        - {iters: 2, timeout: 5.0, retire: true}
        - {iters: 20, timeout: 1.0, retire: true}
        - {iters: 2, timeout: 5.0, retire: true}
        - {iters: 20, timeout: 1.0, retire: true}
        - {iters: 2, timeout: 5.0, retire: true}
        - {iters: 20, timeout: 1.0, retire: true}
        - {iters: 2, timeout: 5.0, retire: true}

    boot_strip:
        percentile: 95
        hard_threshold: 5000
