application:
    mode: estimation
    error_seed: 24
    error_scaling: pop
    alpha_0: -0.001109
    alpha_1: 0.211600
    est_result: boot_pop_scaling/result.json
dimensions:
    n_simulations: 5
subproblem:
    name: QuadraticKnapsackGRB
    gurobi_params:
        TimeLimit: 1.0

row_generation:
    max_iters: 200
    tolerance: .01
    master_gurobi_params:
        Method: 0
    theta_bounds:
        lb: 0
        ub: 1.0

callbacks:
    row_gen:
        - {iters: 50, timeout: 1.0}
        - {timeout: 10.0, retire: true}
