num_agents: 34334
num_items: 20
num_features: 5
num_simuls: 1

tol_certificate: 1e-3

max_iters: 100

subproblem: QuadSupermod
subproblem_settings:
    num_iters_SGM: 10000
    alpha: .005
    method: constant_over_sqrt_k
    parallel_local: true

