num_agents: 34334
num_items: 20
num_features: 6
num_simuls: 1

tol_certificate: 1e-3

max_iters: 100

master_settings:
    OutputFlag: 0
    # ubs: [10,1000,10000,10000,10,10]
    lbs: [0,-100000,0,-1000,0,0]

subproblem_name: QuadSupermod
subproblem_settings:
    num_iters_SGM: 15000
    alpha: 1
    method: constant_over_sqrt_k
    parallel_local: true

