num_agents: 34334
num_items: 20
num_features: 6
num_simuls: 1

tol_certificate: 1e-3

max_iters: 100

master_settings:
    OutputFlag: 1
    ubs: [10,10,10,10,10,10]
    lbs: [null,null,null,null,-1,null]

subproblem_name: QuadLovatz
subproblem_settings:
    num_iters_SGM: 20000
    # alpha: 1
    method: constant_over_sqrt_k
    parallel_local: true
    multithreading: true
    verbose: true

