dimensions:
    num_agents: 13229
    num_items: 50
    num_features: 5
    num_simuls: 1


subproblem: 
    name: QuadSupermodularNetwork
   
row_generation:
    max_iters: 300
    theta_ubs: 1000
    


