num_agents: 255
num_items: 493
num_features: 4
num_simuls: 1

item_fixed_effects: true

max_iters: 2
min_iters: null

subproblem: QuadKnap
subproblem_settings:
    TimeLimit: 100
    MIPGap_tol: 1e-2
