dimensions:
    num_agents: 255
    num_items: 493
    num_features:  497
    num_simuls: 1

subproblem: 
    name: QuadKnapsack
    settings:
        TimeLimit: 100
        MIPGap_tol: 1e-2
row_generation:
    max_iters: 200

