num_agents: 200
num_items: 200
num_features: 4
num_simuls: 1

subproblem: QuadLovatz
subproblem_settings:
    num_iters_SGM: 10000 #15000
    # alpha: 10
    method: constant_over_sqrt_k
    parallel_local: true
    # multithreading: true

