num_agents: 300
num_items: 200
num_features: 5
num_simuls: 1

subproblem: QuadSupermod
subproblem_settings:
    num_iters_SGM: 6000
    alpha: .05
    method: constant_over_sqrt_k
    parallel_local: true

